### ISSUE TITLE
RuntimeError: CUDA error: invalid argument

### ISSUE THREAD

**Issue by Yueziyu** [FZU-N/URWKV#11]
gw = torch.sum(gw, dim=0)
RuntimeError: CUDA error: invalid argument
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

我在使用模型训练时出现上述bug，请问有什么解决方法吗？

**Comment by clue3clue32** [comment]
https://github.com/FZU-N/URWKV/issues/5

**Comment by wwuuyy** [comment]
> gw = torch.sum(gw, dim=0)gw = torch.sum（gw， dim=0） RuntimeError: CUDA error: invalid argumentRuntimeError：CUDA 错误：参数无效 Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.使用 `TORCH_USE_CUDA_DSA` 进行编译以启用设备端断言。
> 
> 我在使用模型训练时出现上述bug，请问有什么解决方法吗？

我也有这个问题 请问你解决了吗？

**Comment by Yueziyu** [comment]
没有




butters
***@***.***

**Comment by Yangzhichen763** [comment]
@Yueziyu @wwuuyy 我之前也遇到了这个问题，可能是CUDA版本和Pytorch的版本不对应。README.md文件中写的是cuda11.3，我服务器上的cuda是11.6，换成11.6就可以了。可以试一下下载和自己服务器CUDA版本对应的pytorch， "ls -l /usr/local/ | grep cuda" 用这个命令查一下

**Comment by Yueziyu** [comment]
我用的2.5.1的pytorch，可能是版本过2.0的即便cuda对应也有问题，我是把cudnn相关的加速禁用了能跑




butters
***@***.***

**Comment by wwuuyy** [comment]
> [@Yueziyu](https://github.com/Yueziyu) [@wwuuyy](https://github.com/wwuuyy) 我之前也遇到了这个问题，可能是CUDA版本和Pytorch的版本不对应。README.md文件中写的是cuda11.3，我服务器上的cuda是11.6，换成11.6就可以了。可以试一下下载和自己服务器CUDA版本对应的pytorch， "ls -l /usr/local/ | grep cuda" 用这个命令查一下

非常感谢 用了你的方法 目前问题已解决 祝你学术顺利！

**Comment by Muzi010** [comment]
> 我用的2.5.1的pytorch，可能是版本过2.0的即便cuda对应也有问题，我是把cudnn相关的加速禁用了能跑
> 
> 
> 
> 
> butters
> ***@***.***

如何禁用的可以说一下么？

**Comment by Muzi010** [comment]
> > [@Yueziyu](https://github.com/Yueziyu) [@wwuuyy](https://github.com/wwuuyy) 我之前也遇到了这个问题，可能是CUDA版本和Pytorch的版本不对应。README.md文件中写的是cuda11.3，我服务器上的cuda是11.6，换成11.6就可以了。可以试一下下载和自己服务器CUDA版本对应的pytorch， "ls -l /usr/local/ | grep cuda" 用这个命令查一下
> 
> 非常感谢 用了你的方法 目前问题已解决 祝你学术顺利！

怎么修改呀，我感觉版本都是对应的，还是报这个错误。

**Comment by Muzi010** [comment]
> [@Yueziyu](https://github.com/Yueziyu) [@wwuuyy](https://github.com/wwuuyy) 我之前也遇到了这个问题，可能是CUDA版本和Pytorch的版本不对应。README.md文件中写的是cuda11.3，我服务器上的cuda是11.6，换成11.6就可以了。可以试一下下载和自己服务器CUDA版本对应的pytorch， "ls -l /usr/local/ | grep cuda" 用这个命令查一下

可以将你的环境打印出来给我看看么
